name: hunter_card_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  hooks_riverpod: ^2.4.6
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.6
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/card_logo.png
    - assets/images/icon.png

